---
title: "Create train and test sets for time series in R"
author: Samuel Bohman
date: '2018-10-04'
slug: create-train-and-test-sets-for-time-series-in-r
categories: []
tags:
  - r
  - time series
  - forecasting
summary: "Prepare a train and a test set for time series with the forecast package."
---

The [forecast](http://pkg.robjhyndman.com/forecast/) package by Rob Hyndman supports since version 8.0 `head` and `tail` for time series. This enables a very handy mechanism for creating train and test sets without the `window` or the `subset` function. All you need is to provide the size of the train set, as exemplified below. 

```{r}
library(forecast)
train <- head(AirPassengers, round(length(AirPassengers) * 0.8))
h <- length(AirPassengers) - length(train)
test <- tail(AirPassengers, h)
```

```{r}
train
```

```{r}
test
```

```{r}
autoplot(train) + autolayer(test)
```

## Links

[https://robjhyndman.com/hyndsight/forecast8/](https://robjhyndman.com/hyndsight/forecast8/)

[https://otexts.org/fpp2/accuracy.html](https://otexts.org/fpp2/accuracy.html)